import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ClubsList from '../components/ClubsList';
import { leagues } from '../../leagues/pages/Leagues';

import ManchesterCity from '../../images/clubs/Manchester_City_FC.png';
import Liverpool from '../../images/clubs/Liverpool_FC.png';

export const clubs = [
  { id: 'c1', name: 'Arsenal', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c2', name: 'Aston Villa', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c3', name: 'Brentford', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c4', name: 'Brighton & Hove Albion', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c5', name: 'Burnley', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c6', name: 'Chelsea', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c7', name: 'Crystal Palace', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c8', name: 'Everton', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c9', name: 'Leeds United', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c10', name: 'Leicester City', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c11', name: 'Liverpool', image: Liverpool, leagueId: 'l1' },
  { id: 'c12', name: 'Manchester City', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c13', name: 'Manchester United', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c14', name: 'Newcastle United', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c15', name: 'Norwich City', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c16', name: 'Southampton', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c17', name: 'Tottenham Hotspur', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c18', name: 'Watford', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c19', name: 'West Ham United', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c20', name: 'Wolverhampton Wanderers', image: ManchesterCity, leagueId: 'l1' },
  { id: 'c21', name: 'Atlético Mineiro', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c22', name: 'Bahia', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c23', name: 'Ceará', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c24', name: 'Chapecoense', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c25', name: 'Corinthians', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c26', name: 'Cuiabá', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c27', name: 'Flamengo', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c28', name: 'Fluminense', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c29', name: 'Fortaleza', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c30', name: 'Grêmio', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c31', name: 'Internacional', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c32', name: 'Juventude', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c33', name: 'Palmeiras', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c34', name: 'Santos', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c35', name: 'São Paulo', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c36', name: 'Sport Recife', image: ManchesterCity, leagueId: 'l2' },
  { id: 'c37', name: 'AC Milan', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c38', name: 'AS Roma', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c39', name: 'Atalanta', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c40', name: 'Bologna', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c41', name: 'Cagliari', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c42', name: 'Empoli', image: ManchesterCity, leagueId: 'l3' },
  { id: 'c43', name: 'Fiorentina', leagueId: 'l3' },
  { id: 'c44', name: 'Genoa', leagueId: 'l3' },
  { id: 'c45', name: 'Hellas Verona', leagueId: 'l3' },
  { id: 'c46', name: 'Inter Milan', leagueId: 'l3' },
  { id: 'c47', name: 'Juventus', leagueId: 'l3' },
  { id: 'c48', name: 'Lazio', leagueId: 'l3' },
  { id: 'c49', name: 'Napoli', leagueId: 'l3' },
  { id: 'c50', name: 'Sampdoria', leagueId: 'l3' },
  { id: 'c51', name: 'Sassuolo', leagueId: 'l3' },
  { id: 'c52', name: 'Spezia', leagueId: 'l3' },
  { id: 'c53', name: 'Torino', leagueId: 'l3' },
  { id: 'c54', name: 'Udinese', leagueId: 'l3' },
  { id: 'c55', name: 'Venezia', leagueId: 'l3' },
  { id: 'c56', name: 'Salernitana', leagueId: 'l3' },
  { id: 'c57', name: 'Angers', leagueId: 'l4' },
  { id: 'c58', name: 'AS Monaco', leagueId: 'l4' },
  { id: 'c59', name: 'Bordeaux', leagueId: 'l4' },
  { id: 'c60', name: 'Brest', leagueId: 'l4' },
  { id: 'c61', name: 'Clermont Foot', leagueId: 'l4' },
  { id: 'c62', name: 'Lille', leagueId: 'l4' },
  { id: 'c63', name: 'Lorient', leagueId: 'l4' },
  { id: 'c64', name: 'Lyon', leagueId: 'l4' },
  { id: 'c65', name: 'Marseille', leagueId: 'l4' },
  { id: 'c66', name: 'Metz', leagueId: 'l4' },
  { id: 'c67', name: 'Montpellier', leagueId: 'l4' },
  { id: 'c68', name: 'Nantes', leagueId: 'l4' },
  { id: 'c69', name: 'Nice', leagueId: 'l4' },
  { id: 'c70', name: 'Paris Saint-Germain', leagueId: 'l4' },
  { id: 'c71', name: 'Rennes', leagueId: 'l4' },
  { id: 'c72', name: 'Saint-Étienne', leagueId: 'l4' },
  { id: 'c73', name: 'Strasbourg', leagueId: 'l4' },
  { id: 'c74', name: 'Troyes', leagueId: 'l4' },
  { id: 'c75', name: 'Lens', leagueId: 'l4' },
  { id: 'c76', name: 'Reims', leagueId: 'l4' },
  { id: 'c77', name: 'Ajax', leagueId: 'l5' },
  { id: 'c78', name: 'AZ Alkmaar', leagueId: 'l5' },
  { id: 'c79', name: 'Cambuur', leagueId: 'l5' },
  { id: 'c80', name: 'FC Emmen', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c81', name: 'FC Groningen', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c82', name: 'FC Twente', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c83', name: 'Feyenoord', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c84', name: 'Fortuna Sittard', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c85', name: 'Go Ahead Eagles', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c86', name: 'Heracles Almelo', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c87', name: 'NEC Nijmegen', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c88', name: 'PEC Zwolle', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c89', name: 'PSV Eindhoven', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c90', name: 'RKC Waalwijk', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c91', name: 'SC Heerenveen', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c92', name: 'Sparta Rotterdam', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c93', name: 'Utrecht', image: ManchesterCity, leagueId: 'l5' },
  { id: 'c94', name: 'Vitesse', leagueId: 'l5' },
  { id: 'c95', name: 'VVV-Venlo', leagueId: 'l5' },
  { id: 'c96', name: 'Willem II', leagueId: 'l5' },
  { id: 'c97', name: 'Alavés', leagueId: 'l6' },
  { id: 'c98', name: 'Athletic Bilbao', leagueId: 'l6' },
  { id: 'c99', name: 'Atlético Madrid', leagueId: 'l6' },
  { id: 'c100', name: 'Barcelona', leagueId: 'l6' },
  { id: 'c101', name: 'Cádiz', leagueId: 'l6' },
  { id: 'c102', name: 'Celta Vigo', leagueId: 'l6' },
  { id: 'c103', name: 'Elche', leagueId: 'l6' },
  { id: 'c104', name: 'Espanyol', leagueId: 'l6' },
  { id: 'c105', name: 'Getafe', leagueId: 'l6' },
  { id: 'c106', name: 'Granada', leagueId: 'l6' },
  { id: 'c107', name: 'Levante', leagueId: 'l6' },
  { id: 'c108', name: 'Mallorca', leagueId: 'l6' },
  { id: 'c109', name: 'Osasuna', leagueId: 'l6' },
  { id: 'c110', name: 'Rayo Vallecano', leagueId: 'l6' },
  { id: 'c111', name: 'Real Betis', leagueId: 'l6' },
  { id: 'c112', name: 'Real Madrid', leagueId: 'l6' },
  { id: 'c113', name: 'Real Sociedad', leagueId: 'l6' },
  { id: 'c114', name: 'Sevilla', image: ManchesterCity, leagueId: 'l6' },
  { id: 'c115', name: 'Valencia', image: ManchesterCity, leagueId: 'l6' },
  { id: 'c116', name: 'Villarreal', image: ManchesterCity, leagueId: 'l6' },
  { id: 'c117', name: 'Belenenses SAD', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c118', name: 'Boavista', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c119', name: 'Braga', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c120', name: 'Estoril', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c121', name: 'Famalicão', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c122', name: 'Gil Vicente', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c123', name: 'Marítimo', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c124', name: 'Moreirense', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c125', name: 'Paços de Ferreira', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c126', name: 'Portimonense', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c127', name: 'Porto', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c128', name: 'Santa Clara', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c129', name: 'Sporting CP', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c130', name: 'Tondela', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c131', name: 'Vitória Guimarães', image: ManchesterCity, leagueId: 'l7' },
  { id: 'c132', name: 'Vitória SC', image: ManchesterCity, leagueId: 'l7' },
];

const Clubs = () => {
  const navigate = useNavigate();

  const { club } = useParams();

  const isValidClub = clubs.some(clubItem => clubItem.name.toLowerCase().replace(/\s+/g, '-') === club);

  if (!isValidClub) {
    navigate('/');
    return null;
  }

  return (
    <div>
      <ClubsList clubs={clubs} leagues={leagues} />
    </div>
  );
};

export default Clubs;
